Translate CSS 2021
Devographics/locale-id-ID pull request #23
Opened 2024-10-09 07:44 UTC by KingSit3

2025-02-12 14:18 UTC, Klrfl requested changes

2025-02-12 14:18 UTC, Klrfl commented on css2021.yml
> +      - **Outreach**: tahun ini, kami menghubungi 23 organisasi yang mereprentasikan pengembang BIPOC dan LGBTQ dengan tujuan untuk bekerja sama. Meski hanya sediki yang membalas, kami akan tetap men
Outreach tidak diterjemahkan kah? ga tau juga sih terjemahannya yang pas apa..

2025-02-12 14:18 UTC, Klrfl commented on css2021.yml
> +      Belakangan ini aku suka bekerja menggunakan Vanilla Extract, itu seperti CSS Modules tapi
'itu seperti' bisa diganti frase lain yang lebih natural, misalnya 'yang mirip seperti' atau apalah

2025-02-12 14:18 UTC, Klrfl commented on css2021.yml
> +      dapat dukungan type secara menyeluruh dengan pengalaman pengembangan yang ajaib.
dapat -> memiliki? magical jangan diterjemahkan secara literal dong, lebih baik 'sangat bagus' atau apa

2025-02-14 03:40 UTC, KingSit3 commented on css2021.yml
> +      - **Outreach**: tahun ini, kami menghubungi 23 organisasi yang mereprentasikan pengembang BIPOC dan LGBTQ dengan tujuan untuk bekerja sama. Meski hanya sediki yang membalas, kami akan tetap men
jadi "menjangkau" sepertinya masuk akal sih

2025-02-14 03:41 UTC, KingSit3 commented on css2021.yml
> +      dapat dukungan type secara menyeluruh dengan pengalaman pengembangan yang ajaib.
ajaib -> menakjubkan

2025-02-15 10:01 UTC, Klrfl approved these changes
merge aja bang

2025-02-15 10:05 UTC, KingSit3 commented
> merge aja bang

woke thanks

2025-02-17 09:32 UTC, merged